### ISSUE TITLE
testing hvac-cli and having a vault fixture

### ISSUE THREAD

**Issue by singuliere** [hvac/hvac-cli#2]
@jeffwecan wrote

> We potentially have cause to work back on this (relatively) ancient hvac issue requesting the Vault integration test harness bits be made reusable via something like a nosetests plugin: hvac/hvac#99. At the very least, if there ends up being enough similar functionality between this repo and hvac, it would make sense to look into. (Though I've also chatted with a friend who have done similar API client + cli tool backed by that client that have good experiences keeping the two pieces of code within the same repo. wave @dbwpe)

**Comment by singuliere** [comment]
hvac-cli is using pytest and there is a [vault server](https://github.com/hvac/hvac-cli/blob/master/tests/conftest.py#L11) fixture that works fine. Although I agree that it would be nice to have this as a separate project, I'm pretty sure I won't do it ;-)

**Comment by singuliere** [comment]
The fixture was improved to support multiple versions of vault. Closing for now but feel free to re-open if you think it should be!

**Comment by jenstroeger** [comment]
Following up on issue https://github.com/hvac/hvac/issues/99 — is the referenced fixture the only way to (kind-of) test the hvac package against a mock test vault?

**Comment by briantist** [comment]
@jenstroeger will respond in the other issue, this repo is slated to be archived soon, see:
- https://github.com/hvac/hvac-cli/issues/17
