### ISSUE TITLE
running the code snippets from the documentation

### ISSUE THREAD

**Issue by singuliere** [hvac/hvac-cli#3]
@jeffwecan wrote
> On the sphinx front, I've actually spent the bulk of my hvac development time over the past month or so implementing doctest after receiving a good deal of documentation typo reports. So I'd recommend checking out that extension if you're interested. I have been pretty pleased with it thus far! https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html

**Comment by singuliere** [comment]
I'll definitely use that, thanks for the hint :-)

**Comment by singuliere** [comment]
Since these are shell snippets, doctest is not the right fit. [Writing Technical Documentation with Sphinx, Paver, and Cog](https://doughellmann.com/blog/2009/02/02/writing-technical-documentation-with-sphinx-paver-and-cog/) suggests [cog](https://nedbatchelder.com/code/cog/) would be a good fit. But it looks like it has not been updated in years.

**Comment by singuliere** [comment]
[autorun](https://github.com/WhyNotHugo/sphinx-autorun) or [shell-doctest](https://bitbucket.org/michilu/shell-doctest) are almost good but not maintained. I've used [cram](https://pypi.org/project/cram/) and the experience was good, in the past. But there is no sphinx extension and it's not been updated in three years.

**Comment by singuliere** [comment]
@jeffwecan unless you have a suggestion I'm tempted to close this as **won't fix**. I don't like the idea that example code is untested but if there is no tooling the best we can do is to carefully test manually.

**Comment by singuliere** [comment]
Ned Batchelder says he still uses [cog](https://nedbatchelder.com/code/cog/) `"to make all my presentations."`

**Comment by jeffwecan** [comment]
Actually yeah in hindsight that makes a lot of sense. I would categorize this as a nice to have in the first place. So if its not immediately implementable it is fine to close out imho.

**Comment by singuliere** [comment]
Let's keep this for later :+1:

**Comment by singuliere** [comment]
For the record cog was recently upgraded and improved

**Comment by briantist** [comment]
https://github.com/hvac/hvac-cli/issues/17
