### ISSUE TITLE
hvac-cli metadata put foo/bar does not create metadata

### ISSUE THREAD

**Issue by singuliere** [hvac/hvac-cli#6]
If the foo/bar secret does not exist, [update_metadata](https://hvac.readthedocs.io/en/stable/source/hvac_api_secrets_engines.html#hvac.api.secrets_engines.KvV2.update_metadata) is documented to set on an existing path. However, the [corresponding API call](https://www.vaultproject.io/api/secret/kv/kv-v2.html#update-metadata) is documented to create metadata even when the secret does not exist. And that is indeed what `vault metadata put` does.

Why is it different when using hvac?

**Comment by jeffwecan** [comment]
To be clear, the concentration here is just about the _documentation_ text that doesn't line up with expectations? If so, it is quite possible I restated things incorrectly in the hvac docstring side of things. When backfilling python / hvac methods to match existing Vault methods, I typically try to do a best-effort first path of things and iterate from there once we start getting feedback from real-world usage.

**Comment by singuliere** [comment]
Ah, that makes a lot of sense. Such differences are fine, I think, as long as they are well documented, which is the case. Closing then :+1:
