### ISSUE TITLE
first release 1.1.0

### ISSUE THREAD

**Issue by singuliere** [hvac/hvac-cli#9]
@jeffwecan now that **vault kv** is fully implemented (modulo one [minor bug](https://github.com/hvac/hvac-cli/issues/6)), I'd like to polish the first release and [created a milestone for 1.1.0](https://github.com/hvac/hvac-cli/milestone/1)) with the remaining tasks.

It's only part of what a full fledged cli needs but it's definitely something I'll use myself because it has workarounds for a few annoying bugs and provides features I need (dump, load, erase).

Does that sound sensible to you?

**Comment by jeffwecan** [comment]
I'm on-board with that line of thinking yes :)

**Comment by singuliere** [comment]
Let's do this ! It's a pleasure working with you @jeffwecan
